fix:  build시 컴파일 에러
mejaiGG/Frontend pull request #9
Opened 2024-04-08 07:27 UTC by donghyun1998

## ✅ 풀\_리퀘스트 체크리스트

- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [ ] commit message 가 적절한지 확인해주세요.
- [ ] 적절한 branch 로 요청했는지 확인해주세요.
- [ ] Assignees, Label 을 붙여주세요.
- [ ] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

무엇을 합니다!

- 이 일을 했다!
- 이 일도 했다!

<br/>

## 📎 변경한 이유

- 이러한 이유 때문에 변경했습니다!

<br/>

closes: #Issue Number

## 👨🏻‍💻 테스트 체크리스트

- 이러한 테스트를 했어요!

<br/>

## 📌 변경 및 주의 사항

<br/>

2024-04-08 07:42 UTC, Hawardshin approved these changes
LGTM고생하셨슴다

2024-04-08 07:42 UTC, Hawardshin commented on src/app/createSubmitHandler.tsx
> +  router: any, // 아니이거 router type이 호환이 안되는디??
검색해보니까 라우터가 타입으로 이슈가 많다네요. any쓰는게 건강에 좋을듯

2024-04-08 07:42 UTC, Hawardshin commented on src/app/summoner-page/page.tsx
> +    </Suspense>
GOOD!

2024-04-08 07:44 UTC, donghyun1998 commented on src/app/createSubmitHandler.tsx
> +  router: any, // 아니이거 router type이 호환이 안되는디??
어쩐지 없더라고요 아놔

2024-04-09 09:15 UTC, kimchijinju requested changes

2024-04-09 09:15 UTC, kimchijinju commented on src/app/createSubmitHandler.tsx
> +  router: any, // 아니이거 router type이 호환이 안되는디??
주석 날려주세요~~

2024-04-09 09:15 UTC, kimchijinju commented on src/app/summoner-page/jandi.tsx
안쓰는 로직 주석으로 관리되는거 굉장히 짜치는 부분입니다. 파일 따로 빼서 관리하거나 아예 날리는게어떨지요

2024-04-09 09:15 UTC, kimchijinju commented on src/components/reactQueryProvider.tsx
> +      {/*<ReactQueryDevtools initialIsOpen={false} position="bottom-right" />*/}
이 주석도 필요없다면 날리면 좋겟습니다.

2024-04-09 09:15 UTC, kimchijinju commented on src/app/summoner-page/fetchFunc.tsx
> +  const [_key, { id, tag, year, month }] = queryKey as [
타입으로 관리하면 더 좋을 것 같읍니다. 비용 많이드는 작업이면 ㄴㄴ

2024-04-09 09:41 UTC, donghyun1998 commented on src/app/summoner-page/jandi.tsx
이거 근데 파일 따로 빼도 빌드에서 에러나던데 어케 관리하나요?
아예 깃 레포에서 제거하라는 말씀이신지

2024-04-09 09:41 UTC, donghyun1998 commented on src/app/createSubmitHandler.tsx
> +  router: any, // 아니이거 router type이 호환이 안되는디??
주석을 아예 적지 않는게 좋나요?
설명이 필요한 부분은 적는게 맞다고 알고있습니다.

2024-04-09 09:43 UTC, donghyun1998 commented on src/components/reactQueryProvider.tsx
> +      {/*<ReactQueryDevtools initialIsOpen={false} position="bottom-right" />*/}
이부분 개발단계에서 react-query로 관리되는 request를 오른쪽 아래에 위젯으로 볼 수 있게 만드는 툴입니다.
배포때 제거하려고 했습니당

2024-04-09 10:47 UTC, kimchijinju commented on src/components/reactQueryProvider.tsx
> +      {/*<ReactQueryDevtools initialIsOpen={false} position="bottom-right" />*/}
확인햇읍니다.

2024-04-09 10:49 UTC, kimchijinju commented on src/app/createSubmitHandler.tsx
> +  router: any, // 아니이거 router type이 호환이 안되는디??
그렇다면 좀더 정제해서 적어주심 좋을 것 같습니다.
따로 문서화 하는것도 방법일것같습니다!!
문서화하기엔 품이 많이드니 잘 정제해서 적으면 좋을것같아요

2024-04-09 10:53 UTC, kimchijinju commented on src/app/summoner-page/jandi.tsx
이부분을 메인브랜치에 합치는건 별로같습니다
메인브랜치가 디벨롭용 브랜치인지 프로덕션용 브랜치인지는 모르겠으나, 둘중 어느용도여도 빼두는게 맞는것 같습니다..
파일 아예 제거하고 커밋하는건 어떠신지요
커밋로그는 남아 확인할 수 있으니..

2024-04-09 13:01 UTC, donghyun1998 commented on src/app/summoner-page/jandi.tsx
납득했습니다
해당 파일 메인에서 지우겠습니다 ^오^b

2024-04-09 13:01 UTC, donghyun1998 commented on src/app/createSubmitHandler.tsx
> +  router: any, // 아니이거 router type이 호환이 안되는디??
남아있는 주석 전부 정제해서 올리도록 하겠습니다

2024-04-10 06:56 UTC, donghyun1998 commented on src/app/summoner-page/fetchFunc.tsx
> +  const [_key, { id, tag, year, month }] = queryKey as [
아래와 같이 타입 분리했습니다. 
``` ts
type JandiQueryKey = [
  string,
  {
    id: string;
    tag: string;
    year: number;
    month: number;
  },
];
```

2024-04-10 07:39 UTC, kimchijinju approved these changes

2024-04-10 07:39 UTC, merged